<rule id="255000" level="12">
	<if_group>sysmon_event_%</if_group>
	<description>RDP Sensitive Settings Changed</description>
	<info type="text">Detects changes to RDP terminal service sensitive settings</info>
	<info type="link">https://blog.menasec.net/2019/02/threat-hunting-rdp-hijacking-via.html</info>
	<group>attack.defense_evasion,MITRE</group>
</rule>
